### ISSUE TITLE
How current rules are parsed into the rules folder

### ISSUE THREAD

**Issue by apuckey** [p0pr0ck5/lua-resty-waf#199]
Could you document what your current process is of translating the mod_security ruleset into the .json files?

I'm trying to figure out the best way to map those rule id's to the rule id's in this application for converting from mod_security to this.

cheers

**Comment by p0pr0ck5** [comment]
Hi,

Sorry for the late reply. The currently included rules were translated by hand when I first created this project (before it was on Github), and they've followed along since. The rule IDs as they exist sort of map 1-1 with the existing OWASP v2 CRS, but I left out a number based on functionality or purpose. They are in need of a rewrite, which is the focus the next few weeks, particularly with the CRS v3.0.0-rc1 drop last week.

Let me know if I can clarify anything :)

**Comment by p0pr0ck5** [comment]
Closing this. For questions like this, feel free to check out our Codewake community page at https://www.codewake.com/p/lua-resty-waf
