### ISSUE TITLE
pre-compiled libraries ?

### ISSUE THREAD

**Issue by mtourne** [p0pr0ck5/lua-resty-waf#206]
Hi, I'm checking out this project but I have mixed feelings about the .so (Linux compiled ?) for libinjection.so and libac.so.
I doubt this would work on my mac, but I haven't yet encountered a failure because of them.

Could you describe what's a failure case, and how to obtain/compile these libraries for other platforms ?

**Comment by p0pr0ck5** [comment]
Hi,

Yes, these are compiled on x64 Linux environments (Ubuntu Trusty). Yeah frankly the inclusion of these libs is just laziness on my part. We do need to change these such that we aren't relying on precompiled libs, either through git submodules or some other method.

* *libinjection* comes from client9: https://github.com/client9/libinjection
* *libac* comes from cloudflare's implementation of Aho-Corasick: https://github.com/cloudflare/lua-aho-corasick

You should be able to compile these yourself, but if you run into hiccups during the compilation process please contact the upstream devs (I remember having to fiddle with the lua-aho-corasick makefile a while ago, I think due to the defined include path for Lua header files). I will retool the make process for lua-resty-waf to avoid having to recompile these for our next tagged release (planning on tagging v0.8.2 within the next two weeks).

As for failure case, have a go at running the unit tests, that should tell you if things are working properly or not.

**Comment by p0pr0ck5** [comment]
Hi,

This is now done on the development branch.

**Comment by mtourne** [comment]
Great! Thank you.
It seems a little rough with MacOS but not impossible so far. I'll send a PR if I have some improvement to contribute.
