### ISSUE TITLE
Default rules not available in opm package

### ISSUE THREAD

**Issue by akaegi** [p0pr0ck5/lua-resty-waf#252]
Tried to install lua-resty-waf from the latest opm package via `opm get p0pr0ck5/lua-resty-waf`
However, the default rules are not installed it seems.
A "find" reveals nothing and the event log says:

> 2017/01/19 17:27:33 [error] 1#1: [lua] waf.lua:586: init(): could not find 11000_whitelist

**Comment by p0pr0ck5** [comment]
Hi,

Sorry for the delayed response. Yeah, OPM support is not great right now (well, it's really not supported at all) because OPM only wants to distribute Lua files, and doesn't really have support for installation hooks (see https://github.com/openresty/opm/issues/30). Honestly we'll probably end up removing lua-resty-waf from OPM for now, or at least documenting some limitations.
